app/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers

app_name='api'
urlpatterns = [
    # path('login', views.login, name='login'),
    # Users endpoints
    path('users/', views.UsersListCreateAPIView.as_view(), name='users-list'),
    path('users/<int:pk>/', views.UsersRetrieveUpdateDestroyAPIView.as_view(), name='users-detail'),
    
    # Posts endpoints
    path('posts/', views.PostsListCreateAPIView.as_view(), name='posts-list'),
    path('posts/<int:pk>/', views.PostsRetrieveUpdateDestroyAPIView.as_view(), name='posts-detail'),
    
    # Comments endpoints
    # path('comments/', views.CommentsListCreateAPIView.as_view(), name='comments-list'),
    path('comments/<int:pk>/', views.CommentsListCreateAPIView.as_view(), name='comments-detail'),
    
    # Friends endpoints
    path('friends/', views.FriendsListCreateAPIView.as_view(), name='friends-list'),
    path('friends/<int:pk>/', views.FriendsRetrieveUpdateDestroyAPIView.as_view(), name='friends-detail'),

    path('register/', views.UserRegistrationAPIView.as_view(), name='user-register'),
    path('login/', views.UserLoginAPIView.as_view(), name='user-login'),
    path('logout/', views.LogoutAPIView.as_view(), name='api-logout'),
    
    path('posts/create/', views.PostsCreateAPIView.as_view(), name='posts-create'),
    
    path('posts/<int:post_id>/comments/', views.CreateCommentAPIView.as_view(), name='post-comments'),

]

kartpostal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('app.urls')),
    path('', include('app.frontend_urls')),
]

app/templates/app/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/site.css' %}">
    <title>Kartpostal | {% block title %}{% endblock %}</title>
  </head>
  <body>
    <div class="container">
      {% block content %}{% endblock %}
    </div>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script> -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdn.tailwindcss.com"></script>
  </body>
</html>

app/templates/app/edit_profile.html
{% extends "app/base.html" %}

{% block title %}
    Edit Profile
{% endblock %}

{% load static %}

{% block content %}
<div class="min-h-screen bg-gray-100 flex">
  {% include "app/navbar.html" %}
  <main class="flex flex-col justify-center ml-48 p-6">
    <form method="post" enctype="multipart/form-data" class="max-w-md mx-auto rounded-lg p-8">
      {% csrf_token %}
      <!-- Profile Picture -->
      <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="profile_picture">Profile Picture</label>
        <input type="file" name="profile_picture" id="profile_picture" class="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
      </div>

      <!-- First Name -->
      <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="first_name">First Name</label>
        <input type="text" name="first_name" id="first_name" value="{{ user.first_name }}" class="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
      </div>

      <!-- Last Name -->
      <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="last_name">Last Name</label>
        <input type="text" name="last_name" id="last_name" value="{{ user.last_name }}" class="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
      </div>

      <!-- Bio -->
      <div class="mb-6">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="bio">Bio</label>
        <textarea name="bio" id="bio" class="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">{{ user.bio }}</textarea>
      </div>

      <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
        Save Changes
      </button>
    </form>
  </main>
</div>
{% endblock %}

app/templates/app/feed.html
{% extends "app/base.html" %}

{% block title %}
    Feed
{% endblock %}

{% load static %}

{% block content %}
<div class="min-h-screen bg-gray-100 flex">
  {% include "app/navbar.html" %}
  <main class="w-3/5 px-4 py-8">
    <div class="rounded-lg bg-[#333333] p-4 space-y-4">
        <div id="messageContainer" style="display: none;">
            <ul class="messages" id="messagesList"></ul>
        </div>
        <form method="post" id="postForm" enctype="multipart/form-data" action="/api/posts/create/">
            {% csrf_token %}
            <div class="flex items-center">
                <input
                    placeholder="What's happening?"
                    class="w-4/5 md:w-3/5 lg:w-2/5 rounded-lg bg-[#222222] p-2 text-sm placeholder-gray-400 border border-gray-400 mr-2"
                    type="text"
                    name="post_text"
                />
                <div class="relative">
                    <input
                        type="file"
                        name="image"
                        class="absolute opacity-0 top-0 left-0 w-full h-full cursor-pointer"
                    />
                    <button type="button" class="inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border border-input bg-background hover:bg-accent hover:text-accent-foreground h-10 px-4 py-2">
                        Choose Image
                    </button>
                </div>
                <input type="hidden" name="user" value="{{ request.user.username }}">
                <button type="button" id="submitPost" class="inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border border-input bg-background hover:bg-accent hover:text-accent-foreground h-10 px-4 py-2 ml-2">Post</button>
            </div>
        </form>
        
      <br>
      <br>
        
      <div class="" id="postsContainer">
    
      </div>

      <!-- <div class="flex space-x-4">
        <img
          src="{% static 'images/kartpostal.png' %}"
          alt="post image"
          class="w-24 h-24 rounded-sm"
          width="48"
          height="48"
          style="aspect-ratio: 48 / 48; object-fit: cover;"
        />
        <div>
          <p class="text-sm">@admin · 2 days ago</p>
          <p>Check out this cute duck!</p>
        </div>
      </div> -->
    </div>
  </main>
</div>

<script>
  document.getElementById('submitPost').addEventListener('click', function(event) {
  event.preventDefault();

  const formData = new FormData(document.getElementById('postForm'));

  fetch('/api/posts/create/', {
    method: 'POST',
    body: formData,
  })
    .then((response) => {
      if (!response.ok) {
        throw new Error('Network response was not ok');
      }
      return response.json();
    })
    .then((data) => {
      // Handle successful response
      console.log(data);
      showMessage("Posted succesfully.", 'success');
      // Optionally, perform actions after posting the data
    })
    .catch((error) => {
      // Handle errors
      console.error('There was an error!', error);
      showMessage("An error occured.", 'error');
    });
});

function showMessage(message, type) {
    messagesList.innerHTML = `<li class="${type}">${message}</li>`;
    messageContainer.style.display = 'block';
}
</script>

<script>
let page = 1; // Initial page number
let isLoading = false;

// Function to fetch and load more posts
function loadMorePosts() {
    if (!isLoading) {
        isLoading = true;
        fetch(`/api/posts/?page=${page}`)
            .then((response) => {
                if (!response.ok) {
                    throw new Error('Network response was not ok');
                }
                return response.json();
            })
            .then((data) => {
                if (data && data.results && Array.isArray(data.results)) {
                    console.log(data);
                    displayPosts(data.results); // Update to use data.results array
                    page++; // Increment the page number for the next load
                } else {
                    throw new Error('Invalid data format');
                }
                isLoading = false;
            })
            .catch((error) => {
                console.error('There was an error!', error);
                isLoading = false;
            });
    }
}

// Function to display posts
function displayPosts(posts) {
    const formatDate = (dateString) => {
      const options = { 
        day: '2-digit',
        month: '2-digit',
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
        hour12: false,
      };
    
      const formattedDate = new Date(dateString).toLocaleString('en-GB', options);
      return formattedDate;
    }; 

    const postsContainer = document.getElementById('postsContainer');

    posts.reverse().forEach((post) => {
        const postDiv = document.createElement('div');
        postDiv.classList.add('border', 'border-indigo-500/75', 'p-4', 'mb-4', 'rounded-xl', 'flex', 'space-x-4');
        postDiv.style.cursor = 'pointer'

        const img = document.createElement('img');
        img.src = post.image ? post.image : '';
        img.alt = 'post image';
        img.classList.add('w-24', 'h-24', 'rounded-sm', 'mr-4');
        img.width = '48';
        img.height = '48';
        img.style = 'aspect-ratio: 48 / 48; object-fit: cover;';

        const postDetailsDiv = document.createElement('div');

        const usernameP = document.createElement('p');

        postDate = formatDate(post.post_date);
        usernameP.textContent = `@${post.user} · ${postDate}`;
        usernameP.classList.add('text-sm');

        const postTextP = document.createElement('p');
        postTextP.textContent = post.post_text;

        postDetailsDiv.appendChild(usernameP);
        postDetailsDiv.appendChild(postTextP);

        postDiv.appendChild(img);
        postDiv.appendChild(postDetailsDiv);

        postDiv.addEventListener('click', function() {
            window.location.href = `/post/${post.post_id}/`;
        });

        postsContainer.appendChild(postDiv);
    });
}

    // Load initial posts
    loadMorePosts();
</script>
{% endblock %}

app/templates/app/login.html
{% extends "app/base.html" %}

{% block title %}
    Login
{% endblock %}

{% load static %}

{% if user.is_authenticated %}
    <script>
        // Redirect the user if authenticated
        window.location.href = '/feed';
    </script>
{% endif %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-4">
            <div class="mt-5">
                <div class="card-body">
                    <form id="loginForm">
                        <!-- Logo -->
                        <img src="{% static 'images/kartpostal.png' %}" alt="Kartpostal Logo" class="mb-4">

                        <!-- Welcome message -->
                        <p class="mb-9">Welcome back, You've been missed</p>

                        <!-- Email input -->
                        <div class="form-group mb-3">
                            <input type="username" class="form-control" name="username" placeholder="Username">
                        </div>

                        <!-- Password input -->
                        <div class="form-group mb-3">
                            <input type="password" class="form-control" name="password" placeholder="Password">
                        </div>

                        <!-- Sign in button -->
                        <button type="submit" class="btn btn-primary btn-block">Sign In</button>

                        <!-- Go to register page -->
                        <div class="mt-3 text-center">
                            <p class="text-muted">Not a Member? <a href="{% url 'app:login' %}" class="font-weight-bold">Register Now</a></p>
                        </div>
                    </form>

                    <!-- Messages container -->
                    <div id="messageContainer" style="display: none;">
                        <ul class="messages" id="messagesList"></ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        const loginForm = document.getElementById('loginForm');
        const messageContainer = document.getElementById('messageContainer');
        const messagesList = document.getElementById('messagesList');

        loginForm.addEventListener('submit', async (event) => {
            event.preventDefault();

            const formData = new FormData(loginForm);
            const data = {
                username: formData.get('username'),
                password: formData.get('password')
            };

            try {
                const response = await fetch('/api/login/', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify(data)
                });

                if (response.ok) {
                    // Handle successful login
                    const responseData = await response.json();
                    console.log(responseData); // Process the response accordingly

                    // Show success message
                    showMessage(responseData.message, 'success');

                    // Redirect after 1 second
                    setTimeout(() => {
                        window.location.href = '/feed';
                    }, 1000);
                } else {
                    // Handle authentication failure
                    console.error('Login failed');

                    // Show error message
                    const errorData = await response.json();
                    showMessage(errorData.message, 'error');
                }
            } catch (error) {
                console.error('Error during login:', error);
            }
        });

        // Function to display messages
        function showMessage(message, type) {
            messagesList.innerHTML = `<li class="${type}">${message}</li>`;
            messageContainer.style.display = 'block';
        }
    </script>
{% endblock %}

app/templates/app/navbar.html
{% load static %}

<aside class="w-64 bg-[#1a1a1a] p-6">
    <a href="/feed/">
        <img src="{% static 'images/kartpostal.png' %}" alt="Kartpostal Logo" class="mb-4">
    </a>
    <nav class="space-y-2 py-16">
        <a href="/feed/" class="flex items-center text-white text-xl py-2">
        <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            class="text-white mr-3"
        >
            <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path>
            <polyline points="9 22 9 12 15 12 15 22"></polyline>
        </svg>
        Home
        </a>
        <a href="" class="flex items-center text-white text-xl py-2">
        <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            class="text-white mr-3"
        >
            <circle cx="11" cy="11" r="8"></circle>
            <path d="m21 21-4.3-4.3"></path>
        </svg>
        Search
        </a>
        <a href="#" class="flex items-center text-white text-xl py-2">
        <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            class="text-white mr-3"
        >
            <path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9"></path>
            <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0"></path>
        </svg>
        Notifications
        </a>
        <a href="/my/" class="flex items-center text-white text-xl py-2">
        <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            class="text-white mr-3"
        >
            <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"></path>
            <circle cx="12" cy="7" r="4"></circle>
        </svg>
        Profile
        </a>
    </nav>
</aside>

app/templates/app/post.html
{% extends "app/base.html" %}

{% block title %}
    Post Details
{% endblock %}

{% load static %}

{% block content %}
<div class="min-h-screen bg-gray-100 flex">
  {% include "app/navbar.html" %}
  <main class="flex-1 pl-32 pr-32 pt-16">
    <div class="p-8 rounded-3xl overflow-hidden">
      <img
        src="{% if post.image %}{{ post.image }}{% else %}/placeholder.svg{% endif %}"
        alt="Post Image"
        class="w-auto h-90 rounded-3xl"
        width="100"
        height="100"
        style="aspect-ratio: 500 / 300; object-fit: cover;"
      />
      <div class="p-2">
        <div class="flex items-center text-sm mb-3">
          <span class="font-bold text-gray-800"><a href="{% url 'app:profile' post.user %}" class="font-bold text-gray-800 mr-2">@{{ post.user }}</a>• {{ post.post_date }}</span>
        </div>
        <h2 class="text-xl font-bold mt-2 mb-2">{{ post.post_text }}</h2>
        <!-- You can adjust the display of post details here -->
       

        <form id="commentForm" method="post" action="{% url 'api:post-comments' post.post_id %}">
          {% csrf_token %}
          <!-- Add fields for comment data -->
          <textarea name="comment_text" class="pl-16 mt-4 border pt-2" placeholder="Enter your comment" required></textarea>
          <input type="hidden" name="user" value="{{ request.user.id }}">
          <!-- Add any other necessary fields -->
      
          <button class="bg-transparent border flex items-center justify-center rounded-full text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-10 px-4 py-2 mt-1 mb-4"
              type="submit">
            Add a comment
          </button>
      </form>
      
        <!-- Add comments here if needed -->
        <!-- Example comment structure -->
        
        <div class="space-y-4" id="commentsContainer">
          <!-- Loop through comments and render each comment -->
          {% if comments %}
            {% for comment in comments %}
              <div class="border-t border-gray-200 pt-4">
                <p class="text-sm">
                  <span class="font-bold text-gray-800 mr-2"><a href="{% url 'app:profile' comment.username %}">@{{ comment.username }}</a></span>
                  <span class="text-gray-500">• {{ comment.comment_date }}</span>
                </p>
                <p class="text-gray-700 mt-1">{{ comment.comment_text }}</p>
                <!-- If comments have children, render them recursively -->
                {% if comment.children %}
                  <div class="pl-4 ml-4 border-l border-gray-200">
                    {% include 'app/comment_tree.html' with comments=comment.children %}
                  </div>
                {% endif %}
              </div>
            {% endfor %}
          {% else %}
            <!-- No comments to display -->
            <p>No comments yet.</p>
          {% endif %}
        </div>        
      </div>
    </div>
  </main>
</div>

<!-- <script>
const path = window.location.pathname; // Get the path part of the URL
const postId = path.split('/')[2];
const commentsContainer = document.getElementById('commentsContainer');

// Fetch comments from your API endpoint
fetch(`/api/comments/${postId}`)
  .then(response => response.json())
  .then(data => {
    const commentsData = data.results; // Get comments from the "results" key
    
    if (!Array.isArray(commentsData)) {
      console.error('Invalid comments data format:', commentsData);
      return;
    }

    // Loop through the commentsData array and create comments
    commentsData.forEach(comment => {
      const commentDiv = document.createElement('div');
      commentDiv.classList.add('border-t', 'border-gray-200', 'pt-4');

      const commentUser = document.createElement('p');
      commentUser.classList.add('text-sm');
      commentUser.innerHTML = `
          <span class="font-bold text-gray-800 mr-2">@${comment.user.username}</span>
          <span class="text-gray-500">• ${comment.comment_date}</span>
      `;

      const commentText = document.createElement('p');
      commentText.classList.add('text-gray-700', 'mt-1');
      commentText.textContent = comment.comment_text;

      commentDiv.appendChild(commentUser);
      commentDiv.appendChild(commentText);

      commentsContainer.appendChild(commentDiv);
    });
  })
  .catch(error => {
    console.error('Error fetching comments:', error);
    // Handle errors if necessary
  });
</script> -->

<script>
document.getElementById('commentForm').addEventListener('submit', async (event) => {
  event.preventDefault();

  const formData = new FormData(event.target); // Get form data

  const formAction = event.target.getAttribute('action');
  const postId = formAction.split('/')[3]; // Extract post ID from form action

  try {
      const response = await fetch(`/api/posts/${postId}/comments/`, {
          method: 'POST',
          headers: {
              'X-CSRFToken': formData.get('csrfmiddlewaretoken'), // Set CSRF token manually
          },
          body: formData,
      });

      if (response.ok) {
          const responseData = await response.json();
          console.log('Comment created:', responseData);
          // Optionally, update UI or perform actions after successful comment creation
      } else {
          console.error('Failed to create comment');
          // Handle errors if needed
      }
      
  } catch (error) {
      console.error('Error creating comment:', error);
      // Handle errors or display error messages
  }

  window.location.reload();
});
</script>
{% endblock %}

app/templates/app/profile.html
{% extends "app/base.html" %}

{% block title %}
    Profile Details
{% endblock %}

{% load static %}

{% block content %}
<div class="min-h-screen bg-gray-100 flex">
  {% include "app/navbar.html" %}
  <main class="flex-1 flex-col justify-center ml-64 mt-16">
    <div class="flex items-center space-x-6 mb-6">
      <span class="relative flex h-28 w-28 shrink-0 overflow-hidden rounded-full">
        <img src="{% static user.profile_picture %}" alt="Profile Picture" class="h-full w-full object-cover" />
      </span>
      <div class="mt-2">
        <h2 class="text-2xl font-semibold">{{ user.username }}</h2>
        <p class="text-md text-gray-400 mb-2">{{ user.first_name }} {{ user.last_name }}</p>

        <p class="text-lg text-gray-600">{{ user.bio }}</p>
        <div class="mt-2 space-x-1">
          {% if request.user.username == request.resolver_match.kwargs.username %}
          <a href="{% url 'app:edit_profile' %}" class="inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 border border-input bg-background hover:bg-accent hover:text-accent-foreground h-10 px-4 py-2">
              Edit profile
          </a>
      {% endif %}
      
          <button type="button" class="inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border border-input bg-background hover:bg-accent hover:text-accent-foreground h-10 px-4 py-2">
            View friends
          </button>
        </div>
      </div>
    </div>
    <div class="flex flex-wrap -mx-1">
    {% for post in user_posts %}
        <div class="w-1/4 p-1 mr-4">
          <a href="/post/{{ post.post_id }}">
            <img
                onclick=""
                src="/{{ post.image }}"
                alt="Post Image"
                class="w-full h-full object-cover rounded-xl"
                style="aspect-ratio: 1 / 1; object-fit: cover;"
            />
          </a>
        </div>
    {% endfor %}
</div>

  </main>
</div>
  {% endblock %}

app/templates/app/register.html
{% extends "app/base.html" %}

{% block title %}
    Register
{% endblock %}

{% load static %}

{% if user.is_authenticated %}
    <script>
        // Redirect the user if authenticated
        window.location.href = '/feed';
    </script>
{% endif %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-4">
            <div class="mt-5">
                <div class="card-body">
                    <form id="registerForm">
                        <!-- Logo -->
                        <img src="{% static 'images/kartpostal.png' %}" alt="Kartpostal Logo" class="mb-4">

                        <!-- Welcome message -->
                        <p class="mb-9">Join us.</p>

                        <!-- Username input -->
                        <div class="form-group mb-3">
                            <input type="text" class="form-control" name="username" placeholder="Username">
                        </div>

                        <!-- Email input -->
                        <div class="form-group mb-3">
                            <input type="email" class="form-control" name="email" placeholder="Email">
                        </div>

                        <!-- Password input -->
                        <div class="form-group mb-3">
                            <input type="password" class="form-control" name="password" placeholder="Password">
                        </div>

                        <!-- Confirm password input -->
                        <div class="form-group mb-3">
                            <input type="password" class="form-control" name="confirm_password" placeholder="Confirm Password">
                        </div>

                        <!-- Register button -->
                        <button type="submit" class="btn btn-primary btn-block">Register</button>

                        <!-- Go to login page -->
                        <div class="mt-3 text-center">
                            <p class="text-muted">Already have an account? <a href="{% url 'app:login' %}" class="font-weight-bold">Log In</a></p>
                        </div>
                    </form>

                    <!-- Messages container -->
                    <div id="messageContainer" style="display: none;">
                        <ul class="messages" id="messagesList"></ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        const registerForm = document.getElementById('registerForm');
        const messageContainer = document.getElementById('messageContainer');
        const messagesList = document.getElementById('messagesList');
    
        registerForm.addEventListener('submit', async (event) => {
            event.preventDefault();
    
            const formData = new FormData(registerForm);
            const password = formData.get('password');
            const confirm_password = formData.get('confirm_password');
    
            if (password !== confirm_password) {
                showMessage("Passwords don't match.", 'error');
                return;
            }
    
            const data = {
                username: formData.get('username'),
                email: formData.get('email'),
                password: password,
                confirm_password: confirm_password
            };
    
            try {
                const response = await fetch('/api/register/', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify(data)
                });
    
                if (response.ok) {    
                    showMessage('Registration completed succesfully.', 'success');
    
                    setTimeout(() => {
                        window.location.href = '/login';
                    }, 1000);
                } else {
                    const errorData = await response.json();
                    showMessage('Registration failed', 'error');
                }
            } catch (error) {
                console.error('Error during registration:', error);
            }
        });
    
        // Function to display messages
        function showMessage(message, type) {
            messagesList.innerHTML = `<li class="${type}">${message}</li>`;
            messageContainer.style.display = 'block';
        }
    </script>    
{% endblock %}